### ISSUE TITLE
finalize first version of the website

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#10]
current version:
http://nicolasrannou.github.io/webapp-core/components/webapp-core/
- reponsive

Needs the following pages:
- Home page
- Introduction page
- Members page
- Contact page
- Software page

Other pages (later and very similar to members page anyway):
- highlights
- live

**Comment by NicolasRannou** [comment]
Layout of members page good enough and responsive enough for now.

Next to be connected to real member data.
Next create the contact page.
Next fix potential bugs (safari layout issues).

Go for 1st release.

Next add Software page.
Next add Highlgihts page.
Next add Live/Calendar page.

**Comment by NicolasRannou** [comment]
- Member page hooked up to spreasheet content.
  http://nicolasrannou.github.io/webapp-core/components/webapp-core/demo.html#mri/members/profile_2/Nicolas__Rannou
- Contact page created.
  http://nicolasrannou.github.io/webapp-core/components/webapp-core/demo.html#mri/contact

Next: Fix bugs and improve home page (1 picture a bit of text is enough. Way too much text now.)

**Comment by NicolasRannou** [comment]
New home page:
http://nicolasrannou.github.io/webapp-core/components/webapp-core/demo.html#welcome/home

Most layout bugs fixed.

Next: Fill with real content.
Next: Feedback from Ellen to know if it is a go?
Next: Fix bugs on different platforms.

**Comment by NicolasRannou** [comment]
home page looking much better:
http://nicolasrannou.github.io/webapp-core/components/webapp-core/demo.html#welcome/home

members page now has separators:
http://nicolasrannou.github.io/webapp-core/components/webapp-core/demo.html#mri/members

only remaining bug on chrome is with the google maps: first page shown works well, next google maps on other pages are messed up...

**Comment by NicolasRannou** [comment]
note for later:
add bg-color transition in #drawerToolbar

**Comment by rudolphpienaar** [comment]
This is looking great, Nico! Also seems very quick and responsive!

**Comment by NicolasRannou** [comment]
OK from Ellen, make sure the content of google docs is consistent as much as possible so Heather can fill it

**Comment by NicolasRannou** [comment]
We are already overdue! Adding urgent label

**Comment by NicolasRannou** [comment]
Waiting for review - http://fnndsc.github.io/fnndsc.babymri.org/

**Comment by rudolphpienaar** [comment]
Ugh... I've been too occupied with other things these last two weeks. Will bump it up!
