### ISSUE TITLE
Shared mouse cursor between viewers

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#102]
We have noticed some strange issues on sharing mouse pointer between collaborating viewers in mi2b2 view. It seems to be OS (i.e. Mac) specific. Not observed in Linux. 

To replicate, setup a collaborating view on Mac between two browsers, A and B. In A, hit <shift> and move pointer. B updates accordingly. Now, in B, hit <shift> and move pointer. The pointer in A does not update.

This did not seem browser specific. Tested on Mac from [Chrome] <--> [Chrome/Firefox]. On Linux between [Chrome/Firefox] <--> [Chrome/Firefox].

@NicolasRannou  Can you see if you get the same results/can replicate?

**Comment by NicolasRannou** [comment]
Strange - it worked properly on my laptop while developing.
The shared cursor for fnndsc.github.io/mi2b2 seems to work properly on my mac + chrome.

Could it be an issue in viewerjs?
Are all events for the pointer events being emitted by XTK?

Please note that the cursor position is not updated if you are outside of the slice. (i.e. if your cursor is not over any physical voxel) Maybe in your tests, in B, you were moving the cursor outside of the slice, therefore the data was not being updated?

**Comment by NicolasRannou** [comment]
We could not reproduce it anymore.
