### ISSUE TITLE
do we need interns?

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#13]
I got 8 resumes yet

**Comment by NicolasRannou** [comment]
next step is to check with Ellen we said right? To know ASAP so we can get the thing started if need to apply for visa.

**Comment by rudolphpienaar** [comment]
Ellen is open to the idea, but hasn't confirmed budget. Basically possible interns would be paid the "standard" rate as if they were US graduates. In other words, no money for travel to/from Europe, no money explicitly for housing. I suggested to Ellen a rate of $25/hour which is about $4,500/month.

Again, she hasn't confirmed on this.

**Comment by NicolasRannou** [comment]
Sounds good!

FYI, It seems that the "minimum wage" for interns in France is about 600 euros/month, which is not much, but almost 10 times less than the standard US graduate rate. http://vosdroits.service-public.fr/professionnels-entreprises/F32131.xhtml

We can see that more in details if confirmed.
(@rudolphpienaar is it fine to talk about numbers in public github?)

**Comment by NicolasRannou** [comment]
I got more than 10 applications now so a first step once we know something would be for them to answer a google survey so we now more about them (in respect to what we are looking for) and after quick interviews

**Comment by rudolphpienaar** [comment]
OK -- why don't you filter these down a bit and then send me the most applicable two or three...?

**Comment by NicolasRannou** [comment]
Sounds good. Will do so using this small form: https://docs.google.com/forms/d/1VJqETFYb_9NWioEeiGvGZVTVPzDzRcspG7JORocV780/viewform

Please have a look and let me know if it looks OK to you.

**Comment by rudolphpienaar** [comment]
Ok -- I edited the form. I made the general theme a bit more conservative, too. Please take a look for any errors, and if you don't find any, send it out. If you're not sure about something, let me know.

**Comment by NicolasRannou** [comment]
I really like it now. Just fixed 2 things (php as backend programming language and a missing comma).

I'll send it out now!

**Comment by NicolasRannou** [comment]
sent!

**Comment by NicolasRannou** [comment]
applications all received

**Comment by rudolphpienaar** [comment]
Current status: Ellen is not sure she has funding for this. All interns on hold.

**Comment by NicolasRannou** [comment]
Interns will come with their own fundings.
