### ISSUE TITLE
pacs pull doesn't always pull everything

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#18]
reported by Borjan:
"
1. Bunch of times, if I select multiple image series to be pulled from the PACS onto CHRIS, not all of them get pulled over. It is really weird and random which doesn't get pulled over. Not sure if this is something that you are aware or not. 
"

**Comment by rudolphpienaar** [comment]
Hey Nico -- any updates?

**Comment by NicolasRannou** [comment]
not fixed yet

**Comment by NicolasRannou** [comment]
We might also consider writing the pacs pull as a separated 'app' somehow, to separate it from the chris code base.

We could use it inside chris but other people could just use the app to pull data without chris.

Just a thought, and it is not for anytime soon :)

**Comment by rudolphpienaar** [comment]
yes -- I like that idea! There is currently the <tt>pacs_pull.bash</tt> that somewhat provides that already.
