### ISSUE TITLE
backup

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#19]
# Backup <tt>rsnapshot</tt> process verify

Check on backup (<tt>rsnapshot</tt>) status on 'pretoria' and 'capetown'.
- I (rudolph) checked on 'pretoria' and backups seemed up to date.
- On 'capetown' it seems as if backups are not running.

**Comment by NicolasRannou** [comment]
Debug steps:

```
// log in
ssh root@capetown
// check cronjobs
cat /etc/cron.d/rsnapshot
// run a test daily backup
/usr/bin/rsnapshot -t daily
```

The last command doesn't return any error, just the commands to be executed.

So I took 1 step back, by checking the content of the /backup directory

```
[root@capetown:x86_64-Linux]/#>ls -als /backup/
total 52
4 drwxrwx--- 13 root root 4096 Feb 12 01:30 .
4 drwxr-xr-x 25 root root 4096 Dec 30 10:45 ..
4 drwxr-xr-x  2 root root 4096 Feb 12 01:30 daily.0
4 drwxr-xr-x  2 root root 4096 Feb 11 01:30 daily.1
4 drwxr-xr-x  2 root root 4096 Feb 10 01:30 daily.2
4 drwxr-xr-x  2 root root 4096 Feb  9 01:30 daily.3
4 drwxr-xr-x  2 root root 4096 Feb  8 01:30 daily.4
4 drwxr-xr-x  2 root root 4096 Feb  7 01:30 daily.5
4 drwxr-xr-x  2 root root 4096 Feb  6 01:30 daily.6
4 drwxr-xr-x  2 root root 4096 Feb  2 01:30 weekly.0
4 drwxr-xr-x  2 root root 4096 Jan 26 01:30 weekly.1
4 drwxr-xr-x  2 root root 4096 Jan 19 01:30 weekly.2
4 drwxr-xr-x  2 root root 4096 Jan 12 01:30 weekly.3
```

Date stamps are OK, which means the backup runs.
What is not good is that those directories are empty whereas it should contain the research, sys and arch directories. (see above output of test command "/usr/bin/rsnapshot -t daily")

```
/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded \
    --rsh=/usr/bin/ssh root@tautona:/neuro/labs/grantlab/research \
    /backup/daily.0/tautona/ 
/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded \
    --rsh=/usr/bin/ssh root@tautona:/neuro/sys /backup/daily.0/tautona/ 
/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded \
    --rsh=/usr/bin/ssh root@tautona:/neuro/arch /backup/daily.0/tautona/ 
touch /backup/daily.0/ 
```

Next step is to run one of these command to see what is going on.

```
/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded \
    --rsh=/usr/bin/ssh root@tautona:/neuro/arch /backup/daily.0/tautona/ 
```

Returns: 

```
root@tautona's password: 
```

Passwordless ssh connection between capetown and tautona was down. After entering the password by end, it seems to work. (currently running). Will fix the passwordless ssh issue as soon as the backup of arch dir is completed.

**Comment by NicolasRannou** [comment]
Stopped the manual backup as it would still be running when people come in the office (slow network then).
- Root Passwordless ssh between capetown and tautona was setup.
- It will start backup tonight.

**Comment by rudolphpienaar** [comment]
wonderful! let's verify it works tomorrow and then we can close.

**Comment by NicolasRannou** [comment]
All good:
tautona

```
root@tautona:/neuro/arch# du -khs .
244G    .
root@tautona:/neuro/sys# du -khs .
440G    .
root@tautona:/neuro/labs/grantlab/research# du -khs .
1.5T    .
```

capetown

```
[root@capetown:x86_64-Linux]...tona/neuro/arch#>du -khs .
244G    .
[root@capetown:x86_64-Linux]...utona/neuro/sys#>du -khs .
440G    .
[root@capetown:x86_64-Linux]...antlab/research#>du -khs .
1.5T    .
```
