### ISSUE TITLE
Update 'oranje'.

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#21]
Host <tt>oranje</tt> is still running Ubuntu 12.01 -- needs to be updated, keeping current behaviour (port forwarding) intact.

**Comment by NicolasRannou** [comment]
I think we do not have to worry about forwarding:
pretoria was forwarding to orange, but now pretoria just handles the incoming data for simplicity and performance (we just use pretoria for backup and to run chris VM right now)

**Comment by rudolphpienaar** [comment]
Ok -- so nothing goes through oranje anymore? In that case I guess we can wipe and install an updated ubuntu!

**Comment by NicolasRannou** [comment]
Nothing goes through orange anymore (maybe only the ZABBIX monitoring tools..?).

Yes agreed a fresh install might be the way to go. Do we have any plan for this machine?

We could just turn it off for 1 week to ensure there is no underlying thing which rely on it. And if not, then wipe it out and reinstall it.

We might just do a regular Ubuntu installation if there is no plan for this (old and not powerful) machine. The point is that when we re-start using it, we might have to reinstall everything again to update Ubuntu.

**Comment by NicolasRannou** [comment]
@rudolphpienaar @jbernal0019 
Machine powered off. It should not have any impact. If in 1 week we know for sure there is no underlying connection/process on oranje, we can reformat it.

```
$ sudo shutdown -h now
```

**Comment by NicolasRannou** [comment]
@rudolphpienaar any plan for this guy? If we just keep it down we can close this issue and open a new one when needed
