### ISSUE TITLE
Update 'ChRIS' operating system on VM

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#22]
Main 'ChRIS' VM is running 12.01 and should be updated to Ubuntu 14.10.

@jbernal0019

**Comment by NicolasRannou** [comment]
@rudolphpienaar can we close this one?

**Comment by rudolphpienaar** [comment]
Currently we're on 14.04... I'm just not sure if we should push it up to 14.10? What do you think?

**Comment by NicolasRannou** [comment]
oh I thought that was the update you did last weekend! I guess we should go for it, there should be minimal changes between 14.04 and 14.10...

**Comment by rudolphpienaar** [comment]
Will update today...

**Comment by rudolphpienaar** [comment]
Ugh... just updated and now autofs isn't working...

**Comment by rudolphpienaar** [comment]
Ok, fixed, as per: <tt>https://bugs.launchpad.net/ubuntu/+source/autofs/+bug/1386869</tt>, comment number 4:

```


In /etc/auto.master if I change:

/net -hosts

to

/net /etc/auto.net

it works...

```

**Comment by NicolasRannou** [comment]
chris not working anymore... probably same things as before have to be fixed.

**Comment by NicolasRannou** [comment]
https://github.com/FNNDSC/projectman/issues/41
