### ISSUE TITLE
chris-tido

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#26]
# <tt>chris-tido</tt> issues with local config

The <tt>chris-tido</tt> VM is up in the BCH network. It has issues with being setup as a local "cluster" since all jobs should run on the VM itself.

Currently:
- FreeSurfer / Slicer / FSL have been installed and configured on the VM
- main <tt>config.inc.php</tt> and <tt>plugin.conf</tt> have been setup/edited
- anon data has been copied to the VM in <tt>~chris/data</tt>

Attempt:
- A simple filesystem browser plugin on <tt>/home/chris/data</tt>

Result:
- Fails.

Detail:
- Essentially, the <tt>chris.run</tt> file has a repeated home dir specitication:

/home/chris//home/chris/src/chrisreloaded/plugins/file_browser/file_browser

**Comment by NicolasRannou** [comment]
Was one issue in the configuration:

``` php
// was
define('CHRIS_SRC', joinPaths(CHRIS_HOME, 'src/chrisreloaded'));
// should have been
define('CHRIS_SRC', joinPaths('src', 'chrisreloaded'));
```

File browser plugin is now working.

Do we want all plugins to work or only a few?

**Comment by NicolasRannou** [comment]
Drag and drop working after fixing couple of issue.
https://github.com/FNNDSC/chrisreloaded/commit/fe0f705707f0194458d85d4a3f5c07ce98e7b4ca
https://github.com/FNNDSC/chrisreloaded/commit/b4aec94267707722687808824390b1b54524e628

**Comment by rudolphpienaar** [comment]
Cool -- I'll take a look. filebrowser and mri_convert are the only ones that are needed really. Will test.

**Comment by rudolphpienaar** [comment]
Seems to work now (after some crun updates)
