### ISSUE TITLE
Generate png thumbnails from representative/test data set.

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#30]
For use in the mi2b2 viewer, generate png thumbnails from the dataset.

**Comment by NicolasRannou** [comment]
We might also want to generate nii.gz from those dcm files? The mi2b2 app should support dcm and nii so might be worth, if those png are generated in a script, to also generate nii, nii.gz, mgz out of it at the same time?

**Comment by rudolphpienaar** [comment]
Good idea...

**Comment by NicolasRannou** [comment]
To do so we use http://support.dcmtk.org/docs/dcmdjpeg.html from dcmtk.
https://github.com/FNNDSC/scripts/blob/master/decompJpegDcmDir

And the page from the wiki:
How do I uncompress a JPEG compressed DICOM?

Make sure to give it the full path, i.e. /neuro/users/banu/target.
The script also requires the DCM images to have a .dcm extension. (http://durban/wiki/index.php/Add_DCM_Extension)
 $> ss
 $> decompJpegDcmDir <FULL_PATH_TO_DCM_DIR>
In the end the proper files you will use (the uncompressed ones) are in the normal path. The bad ones (compressed ones) go under the jpegCompressed folder.

**Comment by NicolasRannou** [comment]
was a typo in the script to decompress DICOM @rudolphpienaar fixed

**Comment by NicolasRannou** [comment]
@rudolphpienaar 
Just using image magic to convert dcm to jpeg works fine.
Needs a script to convert to other file formats:
https://github.com/FNNDSC/med2image

**Comment by rudolphpienaar** [comment]
Done. See 'med2view' project on FNNDSC github.

For now, this is a python project. Thus there is some "server" side processing. In the best case, all this will be done in javascript.

For now, the steps are:
- pre-register all volumes
- generate thumbnails
- convert size of thumbnails to 96x96:

`convert input.jpg -resize 96x96 output.jpg`
