### ISSUE TITLE
TIDO - Timeline?

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#32]
Is there a time line when the project should get started?

**Comment by rudolphpienaar** [comment]
The project has already sort of started. The external consultants have a copy of a ChRIS VM and will get back to me/us on some suggested UI changes, workflow.

**Comment by NicolasRannou** [comment]
sounds good, hopefully they will get back to us soon. We should be very precise in what we want so we can actually use what they provide and build on that.

**Comment by rudolphpienaar** [comment]
Yes.
