### ISSUE TITLE
create mi2b2 demo

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#33]
- create a demo to show the drag/drop principle
- doesn't have to show real images (better if it works of course :))

Demo should be available on the fnndsc.github.io/mi2b2 page

It will be used to get some feedback from users.

**Comment by NicolasRannou** [comment]
@jbernal0019 you can just close it and provide link, I added it just to keep track of things.

**Comment by rudolphpienaar** [comment]
Currently working on linking the different renderers. 

Pending:
- Registering all the nii volumes together?

**Comment by NicolasRannou** [comment]
synchronize view between different users would be nice too!

Yes not sure how we can register all the volume together. Right now XTK uses the slice index to synchronize the views, which needs the number of slices to be consitent between volumes. Soon we will only synchonize the RAS position of the slice and reslice the volume on demand so we do not have this limitation on the number of slices, etc. In theory, all heads are oriented in the same way in the RAS space so might not have to do registration?

**Comment by rudolphpienaar** [comment]
We'd have to register so that when moving through slices in one view, the other views are showing the same slice, right? Otherwise you might be midway through one volume and on another already to at the bottom of volume...

**Comment by NicolasRannou** [comment]
I actually do not know... Since we will be using the RAS coordinate of the slice (versus slice index), if the RAS coordinate system is always centered on the middle of the brain of the patient, it might not even be needed.

I am not sure Steve might have some insights.

Before if we had 2 volumes of different sizes/orientation, slice 120 could be the middle slice in one volume and the bottom slice in another. Now, we will say, "give me the slice at RAS Coordinate (x,y,z)". If in both cases, RAS coordinate (0,0,0) is the center of the image it might be all what we need... Does it make sense?

After it also depends on what they are really looking for....

**Comment by NicolasRannou** [comment]
http://fnndsc.github.io/mi2b2/
