### ISSUE TITLE
investigate need of public server

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#37]
because of the nat issue.

Once done, update Rudolph so we can start setup his home server machine.

**Comment by rudolphpienaar** [comment]
Access to my home Linux box:

ssh -X -p 7778 [rudolph,nicolas]@96.237.51.69

**Comment by NicolasRannou** [comment]
sounds good.

There are also solutions such as xirsys which seem to make sense. There is a limited bandwith with the free plan but me be all what we need. (100mb per month.)

https://my.xirsys.com/dashboard

**Comment by rudolphpienaar** [comment]
OK -- but we can seriously try my home box in the meantime. It's free :-)
