### ISSUE TITLE
test original baby piucture

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#38]

**Comment by rudolphpienaar** [comment]
Hey Nico... can you put the link to the page in this issue :-)

**Comment by NicolasRannou** [comment]
Here it is:
http://nicolasrannou.github.io/webapp-core/components/webapp-core/demo.html#welcome/home

In theory, it is just a matter of pointing to the right location here:
https://docs.google.com/a/babymri.org/spreadsheets/d/1ZIXvH4lmPGYzGkVxbfBvr-kc6dbIiqwbs95VcjqvzWY/edit#gid=0

But issue with the picture is that there is a lot of white/empty background which looks not as good and the picture has to be re-centered. It will need some formatting/processing to have something that looks nice but it is not "our" picture.
Alternatively, we could put it on the left/right of some text, cropped.
https://drive.google.com/file/d/0B8u7h0aKnydhVGladTh1OUlSSVU/view?usp=sharing

The good part is that the core infrastructure to add images directly in the spreadsheet works.

**Comment by rudolphpienaar** [comment]
Are all the google doc pages setup? If so, I'll check with Ellen and ask Heather to start adding content.

**Comment by NicolasRannou** [comment]
It needs a bit of re-formatting and the google maps to be fixed.

So the general layout is OK to Ellen?

**Comment by NicolasRannou** [comment]
OK from Ellen, make sure the content of google docs is consistent as much as possible so Heather can fill it
