### ISSUE TITLE
update to latest polymer

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#39]
0.5.5 has been released!

**Comment by rudolphpienaar** [comment]
Nice...! Any significant changes?

**Comment by NicolasRannou** [comment]
Not really, should be straight forward:
https://blog.polymer-project.org/releases/2015/02/23/release-0.5.5/

**Comment by NicolasRannou** [comment]
0.8 almost there now:
https://blog.polymer-project.org/updates/2015/03/10/updated-site/

**Comment by rudolphpienaar** [comment]
Cool!
