### ISSUE TITLE
chris chpc fully tested

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#40]
The followinf plugins MUST work
- mri_convert
- recon_all
- tractography
- pacs_push (dicom listener)
- NO pacs_pull

**Comment by NicolasRannou** [comment]
was on bug on the ssh port command fixed by:
https://github.com/FNNDSC/chrisreloaded/commit/90d0a1578cf1e09533ca0a9ae3dfac381f4a7ee2

**Comment by NicolasRannou** [comment]
- mri_convert working
- recon_all working

**Comment by rudolphpienaar** [comment]
Great work! We can close this once we've tested chris_push and pacs_push.

**Comment by NicolasRannou** [comment]
we should also remove all the plugins which are not necessary so people do not try to use it

**Comment by NicolasRannou** [comment]
also needs to mimic the remote FS organization:
on the vm:

```
[rpienaar@brain:x86_64-Linux]/$>umask 022
[rpienaar@brain:x86_64-Linux]/$>sudo mkdir -p /lustre/SCRATCH5/cubic
[rpienaar@brain:x86_64-Linux].../SCRATCH5/cubic/chris$>sudo ln -s /home/chris chris
```

**Comment by rudolphpienaar** [comment]
Yes.

**Comment by NicolasRannou** [comment]
Up to date - tests passing - no complains :)
