### ISSUE TITLE
chris fix after update

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#41]
not working anymore
- FIXED: /var/www pointing to wrong location

**Comment by NicolasRannou** [comment]
waiting a bit before closing to make sure everything is working....

**Comment by NicolasRannou** [comment]
clean up sessions:
root@chris:/var/lib/php5# ls -l
total 8
drwxr-xr-x 5 root     root     4096 Mar  3 19:42 modules
-rw------- 1 www-data www-data  440 Mar  5 10:21 sess_efd9s0pl870us6kch1vvaq9tf0
-rw------- 1 www-data www-data    0 Mar  5 10:16 sess_i9qvfa9d33m1t4o2a4600hafv5
-rw------- 1 www-data www-data    0 Mar  5 10:16 sess_krkv5kbb6rhsqfu2mlvgtlojl6
root@chris:/var/lib/php5# rm sess_*

**Comment by NicolasRannou** [comment]
```
chris@chris1404:~/src/chrisreloaded$ sudo chown -R chris /var/log/apache2/
chris@chris1404:~/src/chrisreloaded$ sudo chown -R chris /var/run/apache2*
chris@chris1404:~/src/chrisreloaded$ sudo chown -R chris /var/lock/apache2/
# set user and group to chris
chris@chris1404:~/src/chrisreloaded$ sudo vim /etc/apache2/envvars 
  APACHE_RUN_USER=chris
  APACHE_RUN_GROUP=chris
chris@chris1404:~/src/chrisreloaded$ sudo service apache2 restart
```

**Comment by rudolphpienaar** [comment]
Is this information added to the wiki?

**Comment by NicolasRannou** [comment]
also nedd to update the /var/www directory

```
[root@chris:x86_64-Linux]/var#>rm -rf www
[root@chris:x86_64-Linux]/var#>ln -s /neuro/users/chris/src/chrisreloaded www
```

**Comment by NicolasRannou** [comment]
all dicom listeners xinetd scripts are gone
