### ISSUE TITLE
Add users to ChRIS@brain.chpc.ac.za

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#46]
Add the following users to the ChRIS VM for access to CHPC:
aroos - done
auhlmann - done
fahmed - done
hvsteenbergen - done
jfouche - done
jipser - done
kjames - done
nhorn - done
tngako - done
splessis - done

**Comment by NicolasRannou** [comment]
Commands:

```
$> sudo adduser --gid 100 --uid 2575 aroos
$> sudo usermod -a -G cubic aroos
$> id aroos
uid=2575(aroos) gid=100(users) groups=100(users),501(cubic)
```

**Comment by NicolasRannou** [comment]
all users have been added and have same uid/gids as on sun.chpc.ac.za
