### ISSUE TITLE
ChRIS@brain.chpc.ac.za -- tunnels

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#47]
Investigate tunnels from brain.chpc.ac.za:
- Back to BCH
- To other resources at CHPC, including PACS at Typerberg hospital.

**Comment by rudolphpienaar** [comment]
ssh tunnel from brain --> BCH: 5120

**Comment by NicolasRannou** [comment]
to connect from brain to chis bch, it would be:

```
ssh -p 2444 chris@sun.chpc.ac.za
```

It appears to hang...

mcheck-ssh-chpc.bash keeps the connections OUTSIDE -> CHPC open right?

mcheck-ssh-NMR.bash keeps the connections OUTSIDE -> NRM open right?

in mcheck-ssh-NMR.bash, we have that:

```
./mcheck-ssh-NMR.bash:#TARGETACTION[48]="tunnel.bash --reverse  --from rudolph@${H1}:2444 --to ${CHRISCHPC}:443 --sshArgs '-p 7778'"
./mcheck-ssh-NMR.bash:TARGET_CHECK[48]="tunnel.bash --reverse   --from rudolph@${GATE}:2444 --to ${CHRISCHPC}:443 --isRunning"
./mcheck-ssh-NMR.bash:TARGETACTION[48]="tunnel.bash --reverse   --from rudolph@${GATE}:2444 --to ${CHRISCHPC}:443"
```

Is it correct? (surprised by port 443) or maybe I missed something...

**Comment by rudolphpienaar** [comment]
# Tunnels

## Pathways into BCH

Tunnels INTO BCH are maintained by <tt>tautona</tt> (crontab rudolphpienaar) running script <tt>mcheck-ssh-NMR.bash</tt> and using NMR machines as "entry" points.

## Pathway to BCH from <tt>sun.chpc.ac.za</tt>

On host <tt>sun.chpc.ac.za</tt>, the controlling script is <tt>mcheck-ssh-chpc.bash</tt> and it creates tunnels back to <tt>chris-chpc</tt> @ BCH

```
Tunnel @ 2468 is ssh back to chris-chpc@tch.harvard.edu
Tunnel @ 2444 is https back to chris-chpc@tch.harvard.edu
```

## Pathway to BCH from <tt>brain.chpc.ac.za</tt>

On host <tt>brain.chpc.ac.za</tt>, the controlling script is <tt>mcheck-ssh-brain.bash</tt> and it creates tunnels back to <tt>chris.tch.harvard.edu</tt> and <tt>chris-chpc.tch.harvard.edu</tt>

```
Tunnel @ 2468 is ssh back to chris-chpc@tch.harvard.edu VIA sun.chpc.ac.za
Tunnel @ 2444 is https back to chris-chpc@tch.harvard.edu VIA sun.chpc.ac.za
Tunnel @ 2214 is ssh back to chris@tch.harvard.edu VIA gate.nmr.mgh.harvard.edu
Tunnel @ 4443 is hhtps back to chris@tch.harvard.edu VIA gate.nmr.mgh.harvard.edu
```

**Comment by NicolasRannou** [comment]
great! Thanks!

**Comment by NicolasRannou** [comment]
one last thing, we have to setup tunnels for pushing dicom images from brain to remote chris instances too right?

looks like we also need a tunnel to push dicoms TO brain, because of the firewall:

```
nico@vpn-17218216-126:~$ telnet brain.chpc.ac.za 10502
```

**Comment by NicolasRannou** [comment]
tunnel brain -> chris-chpc not working looks like:
[chris@brain:x86_64-Linux]...c/chrisreloaded$>ssh -p 2468 localhost

**Comment by NicolasRannou** [comment]
tunnels look good now

**Comment by NicolasRannou** [comment]
We just miss:
- tunnel for pacs push from brain -> chris-chpc

@rudolphpienaar: do we need:
- tunnels between brain <-> chris-chpc ?
- tunnel sun -> brain: needed because sun's nodes need to ssh back to brain.

with the chpc cluster setup, the nodes can ONLY see the HEAD node (sun+)

**Comment by NicolasRannou** [comment]
new tunnels:

sun - > brain:22 is sun:5120

**Comment by rudolphpienaar** [comment]
see other issue... forgotten which, for pacs_push tunnels from brain to BCH

**Comment by NicolasRannou** [comment]
brain:10402 --> chris.tch.harvard.edu:10401
brain:10403 --> chris-chpc.tch.harvard.edu:10502

**Comment by NicolasRannou** [comment]
@rudolphpienaar seems a tunnel is down...

```
[chris@brain:x86_64-Linux]...c/chrisreloaded(master@3edc-)$>ssh -p 2468 localhost
ssh: connect to host localhost port 2468: Connection refused
```

**Comment by NicolasRannou** [comment]
All tunnels are working - closing

```
[chris@brain:x86_64-Linux]...c/chrisreloaded(master@3edc-)$>ssh -p 2469 localhost
```
