### ISSUE TITLE
FNNDSC scripts + _common

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#48]
Scripts repos still not updating properly... @NicolasRannou  -- please look into this.

On 'tautona' and 'fnndsc' <tt>npm install</tt> in <tt>/neuro/arch/scripts</tt>

```
npm http GET https://registry.npmjs.org/_common
npm http 404 https://registry.npmjs.org/_common

> scripts@0.0.0 install /neuro/arch/scripts
>  [ ! -L _common ] && ln -s node_modules/_common .;

npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

**Comment by NicolasRannou** [comment]
@rudolphpienaar 

Yes looking into it now, I'll push the changes monday morning when nobody is using it.

It seems there are issues on ubuntu with nodejs and node (which is a not related package)

Will run the following steps:
(need to add bower configuration in the scripts directory first of all.)

// make sure umask is 002 for user who will run the installation

```
toor@tautona:/neuro/arch/scripts$ umask
0002
```

// remove everything

```
sudo apt-get --purge remove node
sudo apt-get --purge remove npm
sudo apt-get --purge remove nodejs
```

// install npm and nodejs ONLY

```
sudo apt-get install nodejs
sudo apt-get install nodejs-legacy
sudo apt-get install npm
```

// install bower to manage packages, will be much better and could get it to work as expect on rc-drno

```
sudo npm -g install bower
```

// and in the scripts directory, we need a bower.json
https://github.com/NicolasRannou/webapp-core/blob/master/bower.json

then to update code in cronjob:

```
git pull origin master
bower update
```

Nice thing about bower:
- can pull any remote git directory
- installs it wherever we want (nodesj installs everything in node_modules/ so it is hacky to create a link to _common directory)

**Comment by NicolasRannou** [comment]
Closed by: https://github.com/FNNDSC/scripts/commit/17d2e8a5d12cf052f4f82866d83ff575407e88ee

Tested.
