### ISSUE TITLE
Generate jpgs of all pulled DICOM data in ChRIS

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#51]
# DICOM -> jpg of existing data

In preparation for a revamped ChRIS UI, with image thumbails in the the feed, and a more interactive feed experience in general, we might consider recursively running 'med2image.py' on the chris/data dir to convert DICOMs to jpg
## Note

Need to have <tt>med2image.py</tt> have a mechanism to only convert the "middle" slice of a DICOM series automatically.

**Comment by NicolasRannou** [comment]
Ideally it is just 1 command in the dicom listener script, after the files have been moved to their right location.

**Comment by rudolphpienaar** [comment]
This will work:

```
med2image.py -i $(/bin/ls -1 *dcm | head -n 1) -o %inputFile%SeriesDescription%ProtocolName -t jpg -s m
```

to convert the "middle" file in a dir of dcms, and give the file the output name:

```
    <inputFile>-<DICOM:SeriesDescription>-<DICOM:ProtocolName>.jpg
```

with non-words and spaces removed from the DICOM tag values and <tt>inputFile</tt> is the name of whatever file was actually converted by the script.

**Comment by NicolasRannou** [comment]
almost there, last question is how do we add the med2image dependency in chris. Will add it as a bower package and integrate all packages in lib directory with bower

**Comment by NicolasRannou** [comment]
![screen shot 2015-03-23 at 11 17 28 am](https://cloud.githubusercontent.com/assets/214063/6777919/56964176-d14e-11e4-8037-e4523cc0b0f9.png)
