### ISSUE TITLE
package/scripts vs src/scripts

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#53]
is there any difference? at chpc we have both which doesn't make sense to me right now...

**Comment by rudolphpienaar** [comment]
No... there is no difference. I added the "standard" arch/scripts purely for my convenience since my .bashrc and .bash_file are setup that way. It could just as well have been a symbolic link, but I also wanted the chris "scripts" to be buffered a bit.

**Comment by NicolasRannou** [comment]
ok!
