### ISSUE TITLE
togetherjs is not supported anymore

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#55]
mozilla labs closed...

best option might be to switch to:
http://xirsys.com/simplewebrtc/

might not be an issue but worth to know....

**Comment by rudolphpienaar** [comment]
Hmmm... yes, I agree. We shouldn't use a framework that is no longer being developed / supported.

**Comment by NicolasRannou** [comment]
http://xirsys.com/simplewebrtc/
easyrtc, etc...

Got to pick the right one.

Needs:
- easy manage the users
- voice
- provide server too?
- room concept
- easy pass messages

Not critical:
- video
- cursor

**Comment by NicolasRannou** [comment]
Not using togetherJS anymore as project is not actively supported. Only useful feature was the built-in chat.
