### ISSUE TITLE
BCH <-> BRAIN CONNECTION TESTS

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#56]
List all tests done.

**TODO**:
- emailing service on brain up?

**Comment by NicolasRannou** [comment]
BCH CHRIS CONFIGURATION:
**GOOD**

```
"BRAIN" => serialize(array(^M
    "sshhost" => "brain.chpc.ac.za",^M
    "sshport" => "22",^M
    "dicomhost" => "brain.chpc.ac.za",^M
    "dicomport" => "10502",^M
    "src"  => "/home/chris/src/chrisreloaded"),
"BCH" => serialize(array(^M
    "sshhost" => "localhost",^M
    "sshport" => "22",^M
    "dicomhost" => "pretoria",^M
    "dicomport" => "10401",^M
    "src"  => "/neuro/users/chris/src/chrisreloaded"))
```

**Comment by NicolasRannou** [comment]
BRAIN CONFIGURATION FILE:
**GOOD**

```
"BCH" => serialize(array(
    "sshhost" => "locahost",
    "sshport" => "2214",
    "dicomhost" => "brain.chpc.ac.za",
    "dicomport" => "10402",
    "src"  => "/neuro/users/chris/src/chrisreloaded")),
"BRAIN" => serialize(array(
    "sshhost" => "localhost",
    "sshport" => "22",
    "dicomhost" => "brain.chpc.ac.za",
    "dicomport" => "10502",
    "src"  => "/home/chris/src/chrisreloaded"))
```

**Comment by NicolasRannou** [comment]
PASSWORDLESS SSH:
**GOOD**

BCH -> BRAIN

```
chris@chris$>ssh chris@brain.chpc.ac.za
```

BRAIN -> BCH

```
[chris@brain:x86_64-Linux]~$>ssh -p 2214 localhost
```

**Comment by NicolasRannou** [comment]
SO NOW ONLY TEST CHRIS_PUSH BECAUSE NEED MORE TUNNELS FOR THE PACS_PUSH

**Comment by NicolasRannou** [comment]
CHRIS PUSH: BCH->BRAIN

TODO, test the mail command on brain. Can it send to the outside world?

![screen shot 2015-03-11 at 12 30 21 pm](https://cloud.githubusercontent.com/assets/214063/6595427/8a6a4014-c7ea-11e4-81c2-bc5e398063f4.png)

Data in expected location on BRAIN:
/home/chris/tmp/Freesurfer.zip
Email link working: **@rudolphpienaar?**

![screen shot 2015-03-11 at 12 30 50 pm](https://cloud.githubusercontent.com/assets/214063/6595430/93cc6e84-c7ea-11e4-8617-c5828479e017.png)
/home/chris/tmp/Freesurfer.zip
Email link working: **NO, email not sent for npm.rannou@...**

**Comment by NicolasRannou** [comment]
CHRIS PUSH: BRAIN -> BCH
![screen shot 2015-03-11 at 1 13 02 pm](https://cloud.githubusercontent.com/assets/214063/6596010/661629ca-c7f0-11e4-8040-ae6037829341.png)
Data in expected location on BCH:
/tmp/rpienaar.zip
Email link working: **@rudolphpienaar**

![screen shot 2015-03-11 at 1 08 11 pm](https://cloud.githubusercontent.com/assets/214063/6595937/b3c2094c-c7ef-11e4-88ed-cf6a945932b3.png)
Data in expected location on BCH:
/tmp/_chrisRun_.zip
Email link working: Yes

**Comment by NicolasRannou** [comment]
PACS PUSH: BRAIN->CHPC
![screen shot 2015-03-11 at 4 04 46 pm](https://cloud.githubusercontent.com/assets/214063/6599165/992f9a54-c808-11e4-9a94-46bd22322e96.png)
Dcm files arrived:

Email link send: **?**

![screen shot 2015-03-11 at 4 05 04 pm](https://cloud.githubusercontent.com/assets/214063/6599170/a1b55fec-c808-11e4-87e6-f082d012e536.png)
Dcm files arrived:

Email link send: **?**

**Comment by NicolasRannou** [comment]
PACS PUSH: BCH -> BRAIN

![screen shot 2015-03-11 at 4 56 13 pm](https://cloud.githubusercontent.com/assets/214063/6600426/ca72db88-c80f-11e4-8f6e-5bcf2f2ea56f.png)
Data in expected location on BRAIN:
/hom/chris/data/RENE_TEST*
Email link working:**?**

![screen shot 2015-03-11 at 4 58 43 pm](https://cloud.githubusercontent.com/assets/214063/6600444/eaf0e986-c80f-11e4-815a-15c72ef8127d.png)
Data in expected location on BRAIN:
/home/chris/data/nvp-5/2015.01.26-000D-nvp*
Email link working:**?**

**Comment by NicolasRannou** [comment]
DEBUGGING:

From Brain push to localhost 10502 OK:
-> Brain listener working
From Brain push to localhost 10502 + anonymization NOT OK:
-> Fix the anonymization on Brain

@rudolphpienaar so something funky going on with the tunnels since From Brain push to localhost 10502 OK?

**Comment by NicolasRannou** [comment]
ANONYMIZATION ERROR ON BRAIN:

There is a /neuro tree dependency...

```
/lustre/SCRATCH5/cubic/chris/packages/scripts/neuro-fs: line 133: /neuro/arch/x86_64-Linux/packages/freesurfer/stable/SetUpFreeSurfer.sh: No such file or directory
/lustre/SCRATCH5/cubic/chris/packages/scripts/neuro-fs: line 134: /neuro/arch/x86_64-Linux/packages/fsl/current/etc/fslconf/fsl.sh: No such file or directory
dcmanon_meta.bash -v 10 -K /neuro/users/chris/anonymize_key/CA_cert.pem -D /home/chris//tmp/3_11_2015_17_30_53-18/0_2015.01.26-000D-OR_NEURO_BRAIN-2865/_chrisInput_//home/chris/users/rpienaar/file_browser/3_11_2015_17_26_37-16/0_2015-03-11-12-26-54/tmp/PROFILE_26_JAN_2015-1555/2015.01.26-000D-OR_NEURO_BRAIN-2865/localizer-localizer-34153 -O /home/chris//tmp/3_11_2015_17_30_53-18/0_2015.01.26-000D-OR_NEURO_BRAIN-2865/localizer-localizer-34153-20150311183119618574-anon 
```

**Comment by rudolphpienaar** [comment]
Will look at this tomorrow... Ugh... previously we probably edited the neuro-fs on the remote cluster, and probably since then we pulled a new update and it reverted.

**Comment by NicolasRannou** [comment]
@rudolphpienaar the anonymization is working now

only pending thing is the emailing service which doens't seem to work on brain, did not investigate yet

**Comment by NicolasRannou** [comment]
PACS PUSH: BRAIN -> BCH

![screen shot 2015-03-17 at 10 32 37 am](https://cloud.githubusercontent.com/assets/214063/6684403/24a6d23c-cc91-11e4-99ab-10f468ce8df3.png)
Data in expected location on BCH:
/neuro/users/chris/data/PROFILE_26_JAN_2015-1555
Email link working:**?**

![screen shot 2015-03-17 at 10 32 52 am](https://cloud.githubusercontent.com/assets/214063/6684406/2a2f7c22-cc91-11e4-9381-aae1519ebf51.png)
Data in expected location on BCH:
/neuro/users/chris/data/nvp-264/2015.01.26-000D-nvp-3002
Email link working:**?**
