### ISSUE TITLE
BCH <-> CHPC CONNECTION TESTS

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#58]
List all tests done.

**TODO**:
- emailing service on brain up?

**Comment by NicolasRannou** [comment]
BCH CHRIS CONFIGURATION:
**GOOD**

```
"CHPC" => serialize(array(^M
    "sshhost" => "chris-chpc",^M
    "sshport" => "22",^M
    "dicomhost" => "chris-chpc",^M
    "dicomport" => "10502",^M
    "src"  => "/home/chris/src/chrisreloaded")),
"BCH" => serialize(array(^M
    "sshhost" => "localhost",^M
    "sshport" => "22",^M
    "dicomhost" => "pretoria",^M
    "dicomport" => "10401",^M
    "src"  => "/neuro/users/chris/src/chrisreloaded"))
```

**Comment by NicolasRannou** [comment]
CHPC CHRIS CONFIGURATION:
**GOOD**

```
"CHPC" => serialize(array(^M
    "sshhost" => "localhost",^M
    "sshport" => "22",^M
    "dicomhost" => "chris-chpc",^M
    "dicomport" => "10502",^M
    "src"  => "/home/chris/src/chrisreloaded")),
"BCH" => serialize(array(^M
    "sshhost" => "chris",^M
    "sshport" => "22",^M
    "dicomhost" => "pretoria",^M
    "dicomport" => "10401",^M
    "src"  => "/neuro/users/chris/src/chrisreloaded"))
```

**Comment by NicolasRannou** [comment]
PASSWORDLESS SSH:
**GOOD**

BCH -> CHPC

```
chris@bch$>ssh chris-chpc
```

CHPC -> BCH

```
[chris@chpc]~$>ssh chris
```

**Comment by NicolasRannou** [comment]
CHRIS PUSH: BCH->CHPC
![screen shot 2015-03-11 at 3 51 34 pm](https://cloud.githubusercontent.com/assets/214063/6598851/a9ef963e-c806-11e4-9752-64f02f859a6b.png)

Data in expected location on CHPC:
/home/chris/tmp/PROFILE_26_JAN_2015-1555.zip
Email link working:**?**

![screen shot 2015-03-11 at 3 51 55 pm](https://cloud.githubusercontent.com/assets/214063/6598847/9d0f9eaa-c806-11e4-9060-0a8f6caced87.png)
Data in expected location on CHPC:
/home/chris/tmp/PROFILE_26_JAN_2015-1555.zip
Email link working:**No, email not sent/ for npm.rannou@...**

**Comment by NicolasRannou** [comment]
CHRIS PUSH: CHPC->BCH

![screen shot 2015-03-11 at 3 56 44 pm](https://cloud.githubusercontent.com/assets/214063/6598980/58b9105a-c807-11e4-8902-b8e1de72fe6d.png)

Data in expected location on BCH:
/tmp/0_0_4777251-006M-M.zip
Email link working: Yes

![screen shot 2015-03-11 at 3 57 03 pm](https://cloud.githubusercontent.com/assets/214063/6598984/5d78ebb0-c807-11e4-8439-aad982b20099.png)

Data in expected location on BCH:
/tmp/0_0_4777251-006M-M.zip
Email link working: Yes

**Comment by NicolasRannou** [comment]
PACS PUSH: BCH->CHPC
![screen shot 2015-03-11 at 4 04 46 pm](https://cloud.githubusercontent.com/assets/214063/6599165/992f9a54-c808-11e4-9a94-46bd22322e96.png)
Dcm files arrived:
/home/chris/data/4844002-9
Email link working: **?**

![screen shot 2015-03-11 at 4 05 04 pm](https://cloud.githubusercontent.com/assets/214063/6599170/a1b55fec-c808-11e4-87e6-f082d012e536.png)
Dcm files arrived:
/home/chris/data/nvp-1/2015.03.10-000D-nvp-12/
Email link working: **?**

**Comment by NicolasRannou** [comment]
PACS PUSH: CHPC->BCH

![screen shot 2015-03-11 at 4 15 58 pm](https://cloud.githubusercontent.com/assets/214063/6599416/f286b73a-c809-11e4-9468-e67415b74a8e.png)

Dcm files arrived:
/neuro/users/chris/data/4844002
Email link working: Yes

![screen shot 2015-03-11 at 4 12 26 pm](https://cloud.githubusercontent.com/assets/214063/6599379/c388a614-c809-11e4-8557-c9801dd7d76d.png)
Dcm files arrived:
/neuro/users/chris/data/nvp-264/2015.03.10-000D-nvp-2932/nvp-nvp-34716
Email link working: Yes

**Comment by rudolphpienaar** [comment]
pacs_push ports from brain --> BCH:

brain:10402 --> chris.tch.harvard.edu:10401
brain:10403 --> chris-chpc.tch.harvard.edu:10502
