### ISSUE TITLE
mi2b2 view on DICOM dir/data

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#59]
# mi2b2view test on DICOM Dir

@jbernal0019: Use the following directory as a test for DICOM data:

```
/neuro/users/rudolphpienaar/projects/MGH-HIE-mi2b2-data/HIE-sample-000D-003D/5806424_knottstennettm_m/20120928_011m_15561875_mribrnwoman
```
## Requirements:
- Thumbnail bar must be created
  *\* This will mean some preprocessing with <tt>med2image.py</tt>
- Image information as per the NIfTI example (MRN, PatientName, etc) must be displayed with each view

**Comment by NicolasRannou** [comment]
By thumbnail bar must be created you mean we should created the jpeg for each dataset?
Which is the convention for the dcm since now we have multiple file names?
Moreover, does mi2b2 app handles the case if multiple series are located in the same directory?

**Comment by jbernal0019** [comment]
Yes Nico. Right now DICOM files are sorted by patientID, studyInstanceUID and seriesInstanceUID by the app module before passing them to the viewer. I think maybe that code should be moved from the app to the viewer itself. The convention for dcm is to name the thumbnail image with the same name as the first dcm file.

**Comment by NicolasRannou** [comment]
@jbernal0019 Can we close this issue?

**Comment by rudolphpienaar** [comment]
Yes!
