### ISSUE TITLE
MGH PLUGINS TEST

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#67]
PLUGINS TO BE TESTED:
(**ALL OTHER PLUGINS SHOULD BE REMOVED**)
- mri_convert - OK
- recon_all - **NOT WORKING - re-running**
- tractography - OK
- mri_deface - OK
- findsession - OK
- pacs_pull - OK
- mail - **NOT WORKING**
- search - OK
- filebrowser - OK
- viewer - OK
- zip - OK
- pacs_push - OK (tested in the connection tests)
- chris_push - OK (tested in the connection tests)

**Comment by NicolasRannou** [comment]
pacs_pull:
**GOOD**
![screen shot 2015-03-18 at 4 22 53 pm](https://cloud.githubusercontent.com/assets/214063/6712184/8bcc5ba8-cd8b-11e4-988e-4f5110e6ab78.png)

**Comment by NicolasRannou** [comment]
viewer:
**GOOD**
![screen shot 2015-03-18 at 4 27 54 pm](https://cloud.githubusercontent.com/assets/214063/6712233/c5a890b2-cd8b-11e4-8088-3f4bd342cf3a.png)

**Comment by NicolasRannou** [comment]
file_browser:
**GOOD**
![screen shot 2015-03-18 at 4 29 35 pm](https://cloud.githubusercontent.com/assets/214063/6712276/055efe30-cd8c-11e4-9ede-35a67a123c64.png)

**Comment by NicolasRannou** [comment]
zip:
**GOOD**
![screen shot 2015-03-18 at 4 32 46 pm](https://cloud.githubusercontent.com/assets/214063/6712376/77c39e36-cd8c-11e4-92e6-6032fdebedc2.png)

**Comment by NicolasRannou** [comment]
search:
**GOOD**

```
[chris@chris:x86_64-Linux]...home/chris/data$>ls 
14.11.05_14_07_13_STD_1.3.12.2.1107.5.2.0.45074-3/  3490109-8/  3534041-10/  3555817-12/  3584359-14/  3643590-16/  3702104-18/  4844002-19/    nvp-4/                  TB002-2/
3045698-1/                                          3498836-9/  3539905-11/  3579400-13/  3612150-15/  3662143-17/  3709816-21/  MVH106254-20/  PROFILE_26_JAN_2015-7/
```

![screen shot 2015-03-18 at 4 34 29 pm](https://cloud.githubusercontent.com/assets/214063/6712408/abdb5678-cd8c-11e4-8653-ba0c29eaf3ae.png)

**Comment by NicolasRannou** [comment]
mri_convert:
**GOOD**
![screen shot 2015-03-18 at 4 40 45 pm](https://cloud.githubusercontent.com/assets/214063/6712579/9039a89c-cd8d-11e4-9595-a4b4c694d44c.png)

**Comment by NicolasRannou** [comment]
tractography:
**GOOD**
![screen shot 2015-03-20 at 9 13 52 am](https://cloud.githubusercontent.com/assets/214063/6748045/8131e544-cee1-11e4-8fca-42f0423ed80d.png)

**Comment by NicolasRannou** [comment]
findsession:
*\* GOOD **
![screen shot 2015-03-20 at 9 16 25 am](https://cloud.githubusercontent.com/assets/214063/6748073/d3de29e2-cee1-11e4-8106-dc8bae094dae.png)

![screen shot 2015-03-20 at 11 41 12 am](https://cloud.githubusercontent.com/assets/214063/6749986/1ad5bb3a-cef6-11e4-8d22-ba665843016e.png)

**Comment by NicolasRannou** [comment]
mri_deface:
**GOOD**
![screen shot 2015-03-20 at 12 49 43 pm](https://cloud.githubusercontent.com/assets/214063/6750934/a9efd2d4-ceff-11e4-90de-5d0ac28e3bb7.png)

**Comment by NicolasRannou** [comment]
@rudolphpienaar MGH was up to date :)

**Comment by rudolphpienaar** [comment]
Cool! Although it's using a slightly older crun, no?

**Comment by NicolasRannou** [comment]
Yes you are right! But most the plugins have been tested with runner.php which is nice already!
