### ISSUE TITLE
upgrade website to polymer 0.8

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#77]
https://www.polymer-project.org/0.8/docs/devguide/experimental.html

there are breaking changes so it should be done only after the .5 version of the website has been released.

**Comment by NicolasRannou** [comment]
we might have to wait for all paper-elements to be available

**Comment by rudolphpienaar** [comment]
OK...

**Comment by NicolasRannou** [comment]
0.9 has been released...
