### ISSUE TITLE
Prettify mi2b2 viewer landing page

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#82]
# Prettify mi2b2 viewer landing page

This is one of those visual design things that seems easy but is really hard. I think I like having the whole page a drop zone (like slicedrop), with maybe some clean fonts/text.

**Comment by NicolasRannou** [comment]
Link to live age for reference:
http://fnndsc.github.io/mi2b2/
1. Content of the page
2. Jquery UI theme

Blue-Green color theme seems appropriate for medical tool

**Comment by NicolasRannou** [comment]
mi2b2 MGH's team working on it. Should get some feedback on Thursday April 30th.
