### ISSUE TITLE
Rework Ashok ChRIS design docs

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#83]
# Reword Ashok ChRIS design docs

Ashok provided some hand sketched design ideas for the next ChRIS UI. These need to be reworked a bit -- mostly they assume a persistent standalone-separate file browser tree to drive plugins... this is not what we want.

**Comment by NicolasRannou** [comment]
Couple of notes as remimder:
- need to take interactive plugins into account
- workflow to add feed as input of a plugin (instead of dcm data) not clear

**Comment by NicolasRannou** [comment]
Also, I am testing the integration of the mi2b2 viewer in-feed and it makes me think that it might be good to have plugin-specific viewers.

We do not let the user which viewer he wants to use (drop down, etc.).

We would have a pacs-pull-viewer, freesurfer-viewer, etc. All those viewers should require is very little configuration and just expect a JSON object as input. There are stand-alone so easily re-usable. Might need some investigation/digging/testing but the more I think about it the more I like the idea. All of of those viewers would be based on our base viewer.

It will probably involve some work on the plugins too (well define inputs-outputs so we have a predictable behavior).

Just starting the discussion, but might be worth to mention to Ashok :)

**Comment by NicolasRannou** [comment]
@rudolphpienaar @jbernal0019 closing this one as @rudolphpienaar sent the slides to Ashok
https://app.emaze.com/@ALOFFRCO/chris_hid#1
