### ISSUE TITLE
Scanner backups running off natal

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#85]
# Status of scanner backups

Check the status of the scanner backups that should be running off <tt>natal</tt>.

**Comment by rudolphpienaar** [comment]
For a start, the backup manager is running off <tt>johannesburg</tt> as <tt>root</tt>.

**Comment by rudolphpienaar** [comment]
Due to issues with <tt>shaka</tt> backup, the scanner backups haven't been running for a while!

**Comment by rudolphpienaar** [comment]
Fixed lots of minor issues:
- lots of old links in /var/root on johannesburg that were pointing to /chb !!
- the (gnu) tar on /opt/local/bin that is part of macports did not output the totals
  - fix was to install tar via homebrew and symlink
- will test via cron tonight.

**Comment by NicolasRannou** [comment]
@rudolphpienaar did the nightly buid work? if so we can close this one!

Also, where does it backup the data?

**Comment by rudolphpienaar** [comment]
Yes! These are working. They are saved actually to a second HD in my desktop machine, 'johannesburg'. This means that periodically the drive gets full and I need to clear it out manually.
