### ISSUE TITLE
create vjs demo

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#9]
in its gh-pages

we could submit it to chrome experiments!

**Comment by NicolasRannou** [comment]
on good tracks.

we can now scroll through slices and code is being reorganized. Next step is to get rid of XTK's parser deps and use XIO instead.
https://github.com/FNNDSC/vjs/commit/6e0ba72eb447aef58996511f3447ff88d0ead050

discuss with @pieper about the widget implementation (especially about limitations with VTK's approach)

**Comment by pieper** [comment]
Sounds very promising!  Can you send a link to the demo?

**Comment by NicolasRannou** [comment]
As soon as the demo it ready :)

I am now getting rid of my custom XTK dependencies. As soon as it is done, we can just link the demo to xtk's latest public version and it will work.

I'll keep you posted but I hope to do that tomorrow (before Thursday's meeting)

**Comment by NicolasRannou** [comment]
dirty demo:
http://fnndsc.github.io/vjs/
*\* there are many bugs **
- to scroll, you still have to put you mouse over the 2D XTK renderer at the bottom right, but working on it.
- the ROI selection generate the graph only on mouse up event.
- this demo will be cleaned up and when it works well, we can submit it as a chrome experiment and use it as a reference for our visualization library (currently based on XTK & ThreeJS)

**Comment by pieper** [comment]
Cool!

Works for me on mac pro chrome, but on older mac air chrome had a webgl
"rats" and firefox crashed entirely.  Probably not enough texture memory.

**Comment by NicolasRannou** [comment]
Yes, we have to check the maximum texture size supported by the browser and find a solution to handle it properly if the texture is too big to be store entirely in the shader.

Maybe using multiple passes in the shader? (http://threejs.org/examples/#webgl_postprocessing_advanced)
(http://www.airtightinteractive.com/2013/02/intro-to-pixel-shaders-in-three-js/)

**Comment by rudolphpienaar** [comment]
Looks great! Just so that I understand... what's the relation between 
xtk and threejs in this demo?

**Comment by NicolasRannou** [comment]
XTK: parse the image
returns array containing the pixels data + IJKToRAS Transform + few more things (max intensity, min intensity, etc.)
basically returns as much info as it can from parsing the file 1 time.

ThreeJS: Given N objects, a camera and an interactor, show "things"

VJS: The glue between XTK and ThreeJS
Get image data returned from XTK
Create new VJS objects such as Volume and Slice.
Those objects can just be passed to ThreeJS to be rendered.
Should also provide custom interactors and cameras to ThreeJS.

**Comment by NicolasRannou** [comment]
Demo is online so closing this issue.

Will open new issue about next step for the demo.
