### ISSUE TITLE
review pull request from BU students

### ISSUE THREAD

**Issue by NicolasRannou** [FNNDSC/projectman#91]
some things to be fixed such as $localhost not useful anymore and crun now supports the --port option!

**Comment by rudolphpienaar** [comment]
The latest crun lives in cruntesting and _common --- it's a bit diverged from the crun currently in production in ChRIS. The "biggest" change is specifying job stdout and stderr _directories_ and not files.

**Comment by NicolasRannou** [comment]
Good to know! Thanks!
