### ISSUE TITLE
Chat in viewerjs

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#99]
# Chat in viewerjs
## Overview

Add a simple text chat widget to viewerjs.

**Comment by rudolphpienaar** [comment]
Mostly done.

There is however an issue with keystrokes being captured by xtk.

In the chat window, the 'q' and 'w' and 'r' (possibly other?) keys are not captured since they are special keys for flipping the view in xtk.

Any ideas, @NicolasRannou

**Comment by NicolasRannou** [comment]
Yes, it is because we "prevent.defaults" 
https://github.com/xtk/X/blob/viewerjs/io/interactor.js#L1211-L1249

We can get rid of it for this special XTK build.

**Comment by NicolasRannou** [comment]
Fixed by:
https://github.com/xtk/X/commit/72dfdce221d69dcc026d44cf767229769cb0787e
